pthread.o: pthread.cc \
 /home/uga/angela.ranola/kos/src/ulib/../testoptions.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/syscalls.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/kostypes.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/pthread.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc /home/uga/angela.ranola/kos/src/ulib/../testoptions.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/syscalls.h \
 /home/uga/angela.ranola/kos/src/ulib/../include/kostypes.h
